import type { FigmaVendorDocument } from '@jay-framework/editor-protocol';
import { rgbToHex, getBackgroundFillsStyle, getStrokeStyles, getBorderRadius } from './utils';

export const CLASS_STYLE_BASELINE_KEY = 'jay-class-style-baseline-v1';

export interface ClassStyleBaseline {
    safe: Record<string, string>;
    layout?: Record<string, string>;
    meta: { source: 'computed-style' | 'static'; version: 1 };
}

export interface OverrideDiffResult {
    overrides: Record<string, string>;
    blocked: Array<{ property: string; baseline: string; current: string }>;
}

/**
 * Properties that may be safely emitted as inline overrides on class-based
 * nodes.  These are visual-only properties that do not affect layout,
 * sizing, or flow — so they cannot break responsive stylesheet rules.
 */
export const SAFE_OVERRIDE_PROPERTIES = new Set([
    'background-color',
    'background-image',
    'color',
    'border-top-color',
    'border-right-color',
    'border-bottom-color',
    'border-left-color',
    'border-top-width',
    'border-right-width',
    'border-bottom-width',
    'border-left-width',
    'border-top-style',
    'border-right-style',
    'border-bottom-style',
    'border-left-style',
    'border-radius',
    'opacity',
]);

/**
 * Properties that are never emitted for class-based nodes because they
 * would break responsive/layout behavior controlled by the stylesheet.
 */
const BLOCKED_LAYOUT_PROPERTIES = new Set([
    'display',
    'position',
    'width',
    'height',
    'min-width',
    'min-height',
    'max-width',
    'max-height',
    'padding',
    'padding-top',
    'padding-right',
    'padding-bottom',
    'padding-left',
    'margin',
    'margin-top',
    'margin-right',
    'margin-bottom',
    'margin-left',
    'flex-direction',
    'flex-grow',
    'flex-shrink',
    'flex-basis',
    'flex-wrap',
    'justify-content',
    'align-items',
    'align-self',
    'gap',
    'column-gap',
    'row-gap',
    'grid-template-columns',
    'grid-template-rows',
    'top',
    'right',
    'bottom',
    'left',
    'font-size',
    'line-height',
    'letter-spacing',
    'box-sizing',
    'overflow',
]);

// ── Normalization helpers ───────────────────────────────────────────

/**
 * Normalize a CSS color value to a canonical `rgb(r, g, b)` or
 * `rgba(r, g, b, a)` form for deterministic comparison.
 */
export function normalizeColor(value: string): string {
    const trimmed = value.trim().toLowerCase();

    const rgbaMatch = trimmed.match(
        /^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+))?\s*\)$/,
    );
    if (rgbaMatch) {
        const [, r, g, b, a] = rgbaMatch;
        if (a !== undefined && parseFloat(a) < 1) {
            return `rgba(${r}, ${g}, ${b}, ${normalizeNumber(a)})`;
        }
        return `rgb(${r}, ${g}, ${b})`;
    }

    const hexMatch = trimmed.match(/^#([0-9a-f]{6,8})$/);
    if (hexMatch) {
        const hex = hexMatch[1];
        const r = parseInt(hex.slice(0, 2), 16);
        const g = parseInt(hex.slice(2, 4), 16);
        const b = parseInt(hex.slice(4, 6), 16);
        if (hex.length === 8) {
            const a = parseInt(hex.slice(6, 8), 16) / 255;
            if (a < 1) return `rgba(${r}, ${g}, ${b}, ${normalizeNumber(String(a))})`;
        }
        return `rgb(${r}, ${g}, ${b})`;
    }

    if (trimmed === 'transparent') return 'rgba(0, 0, 0, 0)';

    return trimmed;
}

/**
 * Normalize a numeric CSS value to consistent precision (2 decimal places,
 * trailing zeros stripped).
 */
export function normalizeNumber(value: string): string {
    const n = parseFloat(value);
    if (isNaN(n)) return value;
    return String(Math.round(n * 100) / 100);
}

/**
 * Normalize a CSS property value for comparison.  Dispatches to
 * type-specific normalizers based on property name.
 */
export function normalizePropertyValue(property: string, value: string): string {
    const trimmed = value.trim();
    if (!trimmed) return '';

    if (property.includes('color') || property === 'background-color') {
        return normalizeColor(trimmed);
    }

    if (property === 'opacity') {
        return normalizeNumber(trimmed);
    }

    if (property.includes('width') && !property.includes('max') && !property.includes('min')) {
        return trimmed.replace(/\.0+px$/, 'px');
    }

    if (property === 'border-radius') {
        return normalizeBorderRadius(trimmed);
    }

    return trimmed.replace(/\s+/g, ' ');
}

function normalizeBorderRadius(value: string): string {
    const parts = value.trim().split(/\s+/);
    if (parts.length === 4 && parts.every((p) => p === parts[0])) {
        return parts[0];
    }
    return parts.join(' ');
}

// ── Extraction: Figma node → safe CSS properties ────────────────────

/**
 * Extract safe CSS property values from a Figma vendor doc node using
 * the same conversion helpers the export pipeline uses.  This ensures
 * baseline and export-time values are generated by identical code paths.
 */
export function extractSafeProperties(node: FigmaVendorDocument): Record<string, string> {
    const props: Record<string, string> = {};

    // Background: always populate both background-color and background-image
    // so the diff can detect gradient → solid transitions and emit both.
    const bgCss = getBackgroundFillsStyle(node);
    const bgProps = parseCssDeclarations(bgCss);
    if (bgProps['background-color']) {
        props['background-color'] = bgProps['background-color'];
        props['background-image'] = 'none';
    } else if (bgProps['background-image']) {
        props['background-image'] = bgProps['background-image'];
        props['background-color'] = 'transparent';
    } else {
        props['background-color'] = 'transparent';
        props['background-image'] = 'none';
    }

    const strokeCss = getStrokeStyles(node);
    const strokeProps = parseCssDeclarations(strokeCss);
    if (strokeProps['border-color']) {
        expandBorderShorthand('border-color', strokeProps['border-color'], props);
    }
    if (strokeProps['border-width']) {
        expandBorderShorthand('border-width', strokeProps['border-width'], props);
    }
    if (strokeProps['border-style']) {
        expandBorderShorthand('border-style', strokeProps['border-style'], props);
    }
    copyIfSafe(strokeProps, props, ['border-color', 'border-width', 'border-style']);

    const radiusCss = getBorderRadius(node);
    const radiusProps = parseCssDeclarations(radiusCss);
    copyIfSafe(radiusProps, props);

    if (node.opacity !== undefined) {
        props['opacity'] = String(node.opacity);
    } else {
        props['opacity'] = '1';
    }

    return props;
}

/**
 * Extract layout properties from a Figma vendor doc node for blocked-change detection.
 * These are never emitted as inline overrides but we track them so we can warn
 * when a designer accidentally edits them.
 */
export function extractLayoutProperties(node: FigmaVendorDocument): Record<string, string> {
    const props: Record<string, string> = {};
    const n = node as any;

    if (n.paddingTop !== undefined) props['padding-top'] = `${n.paddingTop}px`;
    if (n.paddingRight !== undefined) props['padding-right'] = `${n.paddingRight}px`;
    if (n.paddingBottom !== undefined) props['padding-bottom'] = `${n.paddingBottom}px`;
    if (n.paddingLeft !== undefined) props['padding-left'] = `${n.paddingLeft}px`;
    if (n.itemSpacing !== undefined) props['gap'] = `${n.itemSpacing}px`;
    if (n.width !== undefined) props['width'] = `${n.width}px`;
    if (n.height !== undefined) props['height'] = `${n.height}px`;

    return props;
}

function expandBorderShorthand(
    shorthandProp: string,
    value: string,
    target: Record<string, string>,
): void {
    const suffix = shorthandProp.replace('border-', '');
    const sides = ['top', 'right', 'bottom', 'left'];

    // Color and style values may contain spaces (e.g. "rgb(0, 0, 0)"),
    // and getStrokeStyles always emits a single uniform value for all sides.
    // Width values (e.g. "1px 2px 3px 4px") can be safely split.
    if (suffix === 'width') {
        const parts = value.trim().split(/\s+/);
        if (parts.length === 1) {
            for (const side of sides) target[`border-${side}-${suffix}`] = parts[0];
        } else if (parts.length === 4) {
            for (let i = 0; i < 4; i++) target[`border-${sides[i]}-${suffix}`] = parts[i];
        }
    } else {
        const trimmed = value.trim();
        for (const side of sides) target[`border-${side}-${suffix}`] = trimmed;
    }
}

function copyIfSafe(
    source: Record<string, string>,
    target: Record<string, string>,
    exclude?: string[],
): void {
    const excludeSet = exclude ? new Set(exclude) : undefined;
    for (const [prop, value] of Object.entries(source)) {
        if (excludeSet?.has(prop)) continue;
        if (SAFE_OVERRIDE_PROPERTIES.has(prop)) {
            target[prop] = value;
        }
    }
}

// ── Baseline capture and diff ───────────────────────────────────────

/**
 * Build a class-style baseline from a Figma vendor doc node.
 * Returns the JSON string to store in pluginData.
 */
export function buildClassStyleBaseline(
    node: FigmaVendorDocument,
    source: 'computed-style' | 'static',
): string {
    const safe: Record<string, string> = {};
    const raw = extractSafeProperties(node);
    for (const [prop, value] of Object.entries(raw)) {
        safe[prop] = normalizePropertyValue(prop, value);
    }

    const layout: Record<string, string> = {};
    const rawLayout = extractLayoutProperties(node);
    for (const [prop, value] of Object.entries(rawLayout)) {
        layout[prop] = value;
    }

    const baseline: ClassStyleBaseline = { safe, layout, meta: { source, version: 1 } };
    return JSON.stringify(baseline);
}

/**
 * Parse a stored baseline JSON string.
 */
export function parseClassStyleBaseline(json: string): ClassStyleBaseline | null {
    try {
        const parsed = JSON.parse(json);
        if (parsed?.safe && parsed?.meta?.version === 1) return parsed;
        return null;
    } catch {
        return null;
    }
}

/**
 * Diff current Figma node properties against a stored baseline.
 * Returns only changed safe properties (for inline emission) and a
 * list of blocked properties that changed but cannot be emitted.
 */
export function diffClassStyleOverrides(
    baselineJson: string,
    currentNode: FigmaVendorDocument,
): OverrideDiffResult {
    const baseline = parseClassStyleBaseline(baselineJson);
    if (!baseline) {
        return { overrides: {}, blocked: [] };
    }

    const currentRaw = extractSafeProperties(currentNode);
    const overrides: Record<string, string> = {};
    const blocked: OverrideDiffResult['blocked'] = [];

    // Bidirectional diff: check all safe properties from either baseline or current
    const allSafeProps = new Set([
        ...Object.keys(baseline.safe),
        ...Object.keys(currentRaw),
    ]);

    for (const prop of allSafeProps) {
        if (!SAFE_OVERRIDE_PROPERTIES.has(prop)) continue;

        const rawBaseline = baseline.safe[prop] ?? '';
        const rawCurrent = currentRaw[prop] ?? '';
        const normalizedBaseline = rawBaseline ? normalizePropertyValue(prop, rawBaseline) : '';
        const normalizedCurrent = rawCurrent ? normalizePropertyValue(prop, rawCurrent) : '';

        if (normalizedCurrent === normalizedBaseline) continue;

        if (rawCurrent) {
            overrides[prop] = rawCurrent;
        } else {
            overrides[prop] = getCssResetValue(prop);
        }
    }

    // Detect blocked layout property changes
    if (baseline.layout) {
        const currentLayout = extractLayoutProperties(currentNode);
        for (const prop of Object.keys(baseline.layout)) {
            if (!BLOCKED_LAYOUT_PROPERTIES.has(prop)) continue;
            const baseVal = baseline.layout[prop] ?? '';
            const curVal = currentLayout[prop] ?? '';
            if (baseVal !== curVal) {
                blocked.push({ property: prop, baseline: baseVal, current: curVal });
            }
        }
    }

    return { overrides, blocked };
}

function getCssResetValue(prop: string): string {
    if (prop === 'background-image') return 'none';
    if (prop === 'background-color') return 'transparent';
    if (prop === 'opacity') return '1';
    if (prop.includes('width')) return '0';
    if (prop.includes('color')) return 'inherit';
    if (prop.includes('style')) return 'none';
    if (prop === 'border-radius') return '0';
    return 'initial';
}

// ── CSS string parsing ──────────────────────────────────────────────

/**
 * Parse a CSS declaration string (e.g. output from export helpers) into
 * individual property → value pairs.
 */
export function parseCssDeclarations(css: string): Record<string, string> {
    const result: Record<string, string> = {};
    if (!css) return result;

    for (const decl of css.split(';')) {
        const colonIdx = decl.indexOf(':');
        if (colonIdx < 0) continue;
        const prop = decl.slice(0, colonIdx).trim();
        const value = decl.slice(colonIdx + 1).trim();
        if (prop && value) result[prop] = value;
    }
    return result;
}

/**
 * Serialize an overrides map back to a CSS style string for inline emission.
 */
export function overridesToStyleString(overrides: Record<string, string>): string {
    return Object.entries(overrides)
        .map(([prop, value]) => `${prop}: ${value}`)
        .join('; ');
}
