checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: 0

nmMode: hardlinks-local

nodeLinker: node-modules

npmAuthToken: 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

npmMinimalAgeGate: 14d

npmPreapprovedPackages:
  - '@wix/*'

npmRegistryServer: 'https://registry.npmjs.org'
