import fs from 'fs';
import path from 'path';
import {
    generateElementDefinitionFile,
    JAY_IMPORT_RESOLVER,
    parseJayFile,
} from '@jay-framework/compiler-jay-html';
import { getLogger } from '@jay-framework/logger';

/**
 * Generates `page.jay-html.d.ts` for every route page — the page's composed interaction surface
 * (child component refs and DL#198 free refs, which exist only here, not in the data contract).
 * The page's data types and runtime enum values come from the separate `page.jay-contract.d.ts`
 * generated by {@link generateContractDefinitionFiles}. See DL#199.
 */
export async function generatePageDefinitionFiles(
    jayHtmlPaths: string[],
    tsConfigPath: string,
    projectRoot: string,
): Promise<void> {
    for (const jayHtmlPath of jayHtmlPaths) {
        // Check if the page.jay-html file exists
        if (!fs.existsSync(jayHtmlPath)) {
            continue;
        }

        const dirname = path.dirname(jayHtmlPath);
        const filename = path.basename(jayHtmlPath);

        const definitionFilePath = jayHtmlPath + '.d.ts';

        // Check if definition file exists and is up to date
        try {
            const [sourceStats, defStats] = await Promise.all([
                fs.promises.stat(jayHtmlPath),
                fs.promises.stat(definitionFilePath).catch(() => null),
            ]);

            // Skip if definition file exists and is newer than source
            if (defStats && defStats.mtime >= sourceStats.mtime) {
                continue;
            }
        } catch (error) {
            // If we can't check stats, continue with generation
        }

        try {
            const jayHtml = await fs.promises.readFile(jayHtmlPath, 'utf-8');

            // Parse the jay file
            const parsedJayHtml = await parseJayFile(
                jayHtml,
                filename,
                dirname,
                { relativePath: tsConfigPath },
                JAY_IMPORT_RESOLVER,
                projectRoot,
            );

            // Generate the definition file
            const definitionFile = generateElementDefinitionFile(parsedJayHtml);

            if (definitionFile.validations.length > 0) {
                getLogger().warn(
                    `failed to generate .d.ts for ${jayHtmlPath} with validation errors: ${definitionFile.validations.join('\n')}`,
                );
            } else {
                // Save the definition file as page.jay-html.d.ts
                const definitionFilePath = jayHtmlPath + '.d.ts';
                await fs.promises.writeFile(definitionFilePath, definitionFile.val, 'utf-8');
                getLogger().info(`📦 Generated definition file: ${definitionFilePath}`);
            }
        } catch (error) {
            getLogger().error(`Failed to generate definition file for ${jayHtmlPath}: ${error}`);
        }
    }
}
