import express, { Express } from 'express';
import http from 'node:http';
import { mkDevServer } from '@jay-framework/dev-server';
import getPort from 'get-port';
import path from 'path';
import fs from 'fs';
import { loadConfig, getConfigWithDefaults } from './config';
import { generatePageDefinitionFiles } from './generate-page-definition-files';
import { getLogger, type LogLevel } from '@jay-framework/logger';

export interface StartDevServerOptions {
    projectPath?: string;
    testMode?: boolean;
    timeout?: number;
    logLevel?: LogLevel;
}

export async function startDevServer(options: StartDevServerOptions = {}) {
    const projectPath = options.projectPath || process.cwd();

    if (projectPath !== process.cwd()) {
        process.chdir(projectPath);
    }

    const config = loadConfig();
    const resolvedConfig = getConfigWithDefaults(config);

    const jayOptions = {
        tsConfigFilePath: './tsconfig.json',
        outputDir: 'build',
    };

    const app: Express = express();
    const httpServer = http.createServer(app);
    const devServerPort = await getPort({ port: resolvedConfig.devServer.portRange });

    const log = getLogger();

    const { server, viteServer, routes, service } = await mkDevServer({
        pagesRootFolder: path.resolve(resolvedConfig.devServer.pagesBase),
        projectRootFolder: process.cwd(),
        publicBaseUrlPath: '/',
        jayRollupConfig: jayOptions,
        logLevel: options.logLevel,
        httpServer,
    });

    app.use(server);

    // Dev sitemap placeholder — only if no static sitemap.xml exists in public/
    const publicPath = path.resolve(resolvedConfig.devServer.publicFolder);
    if (!fs.existsSync(path.join(publicPath, 'sitemap.xml'))) {
        app.get('/sitemap.xml', (_req, res) => {
            res.type('application/xml').send(
                '<?xml version="1.0" encoding="UTF-8"?>\n' +
                    '<!-- Sitemap is generated by the production server from the route manifest. -->\n' +
                    '<!-- Run jay-stack build && jay-stack serve to see the full sitemap. -->\n' +
                    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" />\n',
            );
        });
    }

    // Serve static files from public folder
    if (fs.existsSync(publicPath)) {
        app.use(express.static(publicPath));
    } else {
        log.important(`⚠️  Public folder not found: ${resolvedConfig.devServer.publicFolder}`);
    }

    // Serve HTML — initial routes; new routes register via service.refreshRoutes()
    routes.forEach((route) => {
        app.get(route.path, route.handler);
    });
    service.attachRouteRegistrar((added) => {
        added.forEach((route) => {
            app.get(route.path, route.handler);
        });
    });

    generatePageDefinitionFiles(routes, jayOptions.tsConfigFilePath, process.cwd());

    httpServer.listen(devServerPort, () => {
        log.important(`🚀 Jay Stack dev server started successfully!`);
        log.important(`📱 Dev Server: http://localhost:${devServerPort}`);
        log.important(`📁 Pages directory: ${resolvedConfig.devServer.pagesBase}`);
        if (fs.existsSync(publicPath)) {
            log.important(`📁 Public folder: ${resolvedConfig.devServer.publicFolder}`);
        }
        if (options.testMode) {
            log.important(`🧪 Test Mode: enabled`);
            log.important(`   Health: http://localhost:${devServerPort}/_jay/health`);
            log.important(
                `   Shutdown: curl -X POST http://localhost:${devServerPort}/_jay/shutdown`,
            );
            if (options.timeout) {
                log.important(`   Timeout: ${options.timeout}s`);
            }
        }
    });

    const shutdown = async () => {
        log.important('\n🛑 Shutting down servers...');
        httpServer.closeAllConnections();
        await new Promise((resolve) => httpServer.close(resolve));
        process.exit(0);
    };

    if (options.testMode) {
        app.get('/_jay/health', (_req, res) => {
            res.json({
                status: 'ready',
                port: devServerPort,
                uptime: process.uptime(),
            });
        });

        app.post('/_jay/shutdown', async (_req, res) => {
            res.json({ status: 'shutting_down' });
            setTimeout(async () => {
                await shutdown();
            }, 100);
        });

        if (options.timeout) {
            setTimeout(async () => {
                log.important(`\n⏰ Timeout (${options.timeout}s) reached, shutting down...`);
                await shutdown();
            }, options.timeout * 1000);
        }
    }

    process.on('SIGTERM', shutdown);
    process.on('SIGINT', shutdown);
}
