import { DevServerPagePart } from './load-page-parts';
import type { TrackByMap } from '@jay-framework/view-state-merge';
import type { PluginClientInitInfo } from './plugin-init-discovery';

/**
 * Information needed to generate client init script for the project.
 */
export interface ProjectClientInitInfo {
    /** Import path for the init module */
    importPath: string;
    /** Export name for the JayInit constant (default: 'init') */
    initExport?: string;
}

/**
 * Options for client script generation.
 */
export interface GenerateClientScriptOptions {
    /** Enable automation integration (default: true in dev mode) */
    enableAutomation?: boolean;
    /**
     * Slow ViewState that was baked into the pre-rendered jay-html.
     * When provided, this is merged with fastViewState for the automation API
     * so that AI/automation tools can see the complete page state.
     */
    slowViewState?: object;
}

/**
 * Shared fragments generated by buildScriptFragments().
 * Used by both generateClientScript() and generateHydrationScript().
 */
export interface ScriptFragments {
    partImports: string;
    compositeParts: string;
    pluginClientInitImports: string;
    projectInitImport: string;
    clientInitExecution: string;
    automationImport: string;
    slowViewStateDecl: string;
}

/**
 * Build the shared script fragments used by both client and hydration scripts.
 */
export function buildScriptFragments(
    parts: DevServerPagePart[],
    clientInitData: Record<string, Record<string, any>>,
    projectInit: ProjectClientInitInfo | undefined,
    pluginInits: PluginClientInitInfo[],
    options: GenerateClientScriptOptions,
): ScriptFragments {
    const { enableAutomation = true, slowViewState } = options;
    const hasSlowViewState = slowViewState && Object.keys(slowViewState).length > 0;

    const partImports =
        parts.length > 0 ? parts.map((part) => part.clientImport).join('\n') + '\n' : '';
    const compositeParts =
        parts.length > 0
            ? `[
${parts.map((part) => '        ' + part.clientPart).join(',\n')}
        ]`
            : '[]';

    const hasClientInit = projectInit || pluginInits.length > 0;

    const pluginClientInitImports = pluginInits
        .map((plugin, idx) => {
            return `import { ${plugin.initExport} as jayInit${idx} } from "${plugin.importPath}";`;
        })
        .join('\n      ');

    const projectInitImport = projectInit
        ? `import { ${projectInit.initExport || 'init'} as projectJayInit } from "${projectInit.importPath}";`
        : '';

    const pluginClientInitCalls = pluginInits
        .map((plugin, idx) => {
            const pluginData = clientInitData[plugin.name] || {};
            return `if (typeof jayInit${idx}._clientInit === 'function') {
        console.log('[DevServer] Running client init: ${plugin.name}');
        await jayInit${idx}._clientInit(${JSON.stringify(pluginData)});
      }`;
        })
        .join('\n      ');

    const projectInitCall = projectInit
        ? `if (typeof projectJayInit._clientInit === 'function') {
        console.log('[DevServer] Running client init: project');
        const projectData = ${JSON.stringify(clientInitData['project'] || {})};
        await projectJayInit._clientInit(projectData);
      }`
        : '';

    const clientInitExecution = hasClientInit
        ? `
      // Plugin client initialization (in dependency order)
      ${pluginClientInitCalls}

      // Project client initialization
      ${projectInitCall}
`
        : '';

    const automationImport = enableAutomation
        ? hasSlowViewState
            ? `import { wrapWithAutomation, AUTOMATION_CONTEXT } from "@jay-framework/runtime-automation";
      import { registerGlobalContext } from "@jay-framework/runtime";
      import { deepMergeViewStates } from "@jay-framework/view-state-merge";`
            : `import { wrapWithAutomation, AUTOMATION_CONTEXT } from "@jay-framework/runtime-automation";
      import { registerGlobalContext } from "@jay-framework/runtime";`
        : '';

    const slowViewStateDecl =
        enableAutomation && hasSlowViewState
            ? `const slowViewState = ${JSON.stringify(slowViewState)};`
            : '';

    return {
        partImports,
        compositeParts,
        pluginClientInitImports,
        projectInitImport,
        clientInitExecution,
        automationImport,
        slowViewStateDecl,
    };
}

/**
 * Generate the automation wrapping code.
 * @param mode - 'client' appends to DOM; 'hydrate' skips appendChild (DOM already present)
 */
export function buildAutomationWrap(
    options: GenerateClientScriptOptions,
    mode: 'client' | 'hydrate',
): string {
    const { enableAutomation = true, slowViewState } = options;
    const hasSlowViewState = slowViewState && Object.keys(slowViewState).length > 0;
    const appendDom = mode === 'client';

    if (!enableAutomation) {
        return appendDom ? `\n      target.appendChild(instance.element.dom);` : '';
    }

    const appendLine = appendDom ? `\n      target.appendChild(wrapped.element.dom);` : '';

    if (hasSlowViewState) {
        return `
      // Wrap with automation for dev tooling
      // Deep merge slow+fast ViewState so automation can see full page state
      const fullViewState = deepMergeViewStates(slowViewState, {...viewState, ...fastCarryForward}, trackByMap);
      const wrapped = wrapWithAutomation(instance, { initialViewState: fullViewState, trackByMap });
      registerGlobalContext(AUTOMATION_CONTEXT, wrapped.automation);
      window.__jay = window.__jay || {};
      window.__jay.automation = wrapped.automation;${appendLine}`;
    }

    return `
      // Wrap with automation for dev tooling
      const wrapped = wrapWithAutomation(instance);
      registerGlobalContext(AUTOMATION_CONTEXT, wrapped.automation);
      window.__jay = window.__jay || {};
      window.__jay.automation = wrapped.automation;${appendLine}`;
}

export function generateClientScript(
    defaultViewState: object,
    fastCarryForward: object,
    parts: DevServerPagePart[],
    jayHtmlPath: string,
    trackByMap: TrackByMap = {},
    clientInitData: Record<string, Record<string, any>> = {},
    projectInit?: ProjectClientInitInfo,
    pluginInits: PluginClientInitInfo[] = [],
    options: GenerateClientScriptOptions = {},
) {
    const f = buildScriptFragments(parts, clientInitData, projectInit, pluginInits, options);
    const automationWrap = buildAutomationWrap(options, 'client');

    return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + TS</title>
  </head>
  <body>
    <div id="target"></div>
    <script type="module">
      import {makeCompositeJayComponent} from "@jay-framework/stack-client-runtime";
      ${f.automationImport}
      ${f.pluginClientInitImports}
      ${f.projectInitImport}
      import { render } from '${jayHtmlPath}';
      ${f.partImports}${f.slowViewStateDecl}
      const viewState = ${JSON.stringify(defaultViewState)};
      const fastCarryForward = ${JSON.stringify(fastCarryForward)};
      const trackByMap = ${JSON.stringify(trackByMap)};
${f.clientInitExecution}
      const target = document.getElementById('target');
      const pageComp = makeCompositeJayComponent(render, viewState, fastCarryForward, ${f.compositeParts}, trackByMap)

      const instance = pageComp({/* placeholder for page props */})
${automationWrap}
    </script>
  </body>
</html>`;
}
