import { DevServerPagePart } from './load-page-parts';
import type { TrackByMap } from '@jay-framework/view-state-merge';
import type { PluginClientInitInfo } from './plugin-init-discovery';

/**
 * Generate JS code to reconstruct Promise.resolve()/Promise.reject() for async ViewState properties.
 * JSON.stringify drops Promise objects, so this emits assignments that recreate them from tracked outcomes.
 */
export function generatePromiseReconstruction(
    outcomes: Array<{ id: string; status: 'resolved' | 'rejected'; value: any }>,
): string {
    if (outcomes.length === 0) return '';
    return (
        outcomes
            .map((outcome) => {
                if (outcome.status === 'resolved') {
                    return `      viewState[${JSON.stringify(outcome.id)}] = Promise.resolve(${JSON.stringify(outcome.value)});`;
                } else {
                    const errMsg = outcome.value?.message ?? 'Unknown error';
                    return `      viewState[${JSON.stringify(outcome.id)}] = Promise.reject(new Error(${JSON.stringify(errMsg)}));`;
                }
            })
            .join('\n') + '\n'
    );
}

/**
 * Information needed to generate client init script for the project.
 */
export interface ProjectClientInitInfo {
    /** Import path for the init module */
    importPath: string;
    /** Export name for the JayInit constant (default: 'init') */
    initExport?: string;
}

/**
 * Options for client script generation.
 */
export interface GenerateClientScriptOptions {
    /** Enable automation integration (default: true in dev mode) */
    enableAutomation?: boolean;
    /**
     * Slow ViewState that was baked into the pre-rendered jay-html.
     * When provided, this is merged with fastViewState for the automation API
     * so that AI/automation tools can see the complete page state.
     */
    slowViewState?: object;
}

/**
 * Shared fragments generated by buildScriptFragments().
 * Used by both generateClientScript() and generateHydrationScript().
 */
export interface ScriptFragments {
    partImports: string;
    compositeParts: string;
    pluginClientInitImports: string;
    projectInitImport: string;
    clientInitExecution: string;
    automationImport: string;
    slowViewStateDecl: string;
}

/**
 * Build the shared script fragments used by both client and hydration scripts.
 */
export function buildScriptFragments(
    parts: DevServerPagePart[],
    clientInitData: Record<string, Record<string, any>>,
    projectInit: ProjectClientInitInfo | undefined,
    pluginInits: PluginClientInitInfo[],
    options: GenerateClientScriptOptions,
): ScriptFragments {
    const { enableAutomation = true, slowViewState } = options;
    const hasSlowViewState = slowViewState && Object.keys(slowViewState).length > 0;

    const partImports =
        parts.length > 0 ? parts.map((part) => part.clientImport).join('\n') + '\n' : '';
    const compositeParts =
        parts.length > 0
            ? `[
${parts.map((part) => '        ' + part.clientPart).join(',\n')}
        ]`
            : '[]';

    const hasClientInit = projectInit || pluginInits.length > 0;

    const pluginClientInitImports = pluginInits
        .map((plugin, idx) => {
            return `import { ${plugin.initExport} as jayInit${idx} } from "${plugin.importPath}";`;
        })
        .join('\n      ');

    const projectInitImport = projectInit
        ? `import { ${projectInit.initExport || 'init'} as projectJayInit } from "${projectInit.importPath}";`
        : '';

    const pluginClientInitCalls = pluginInits
        .map((plugin, idx) => {
            const pluginData = clientInitData[plugin.name] || {};
            return `if (typeof jayInit${idx}._clientInit === 'function') {
        console.log('[DevServer] Running client init: ${plugin.name}');
        await jayInit${idx}._clientInit(${JSON.stringify(pluginData)});
      }`;
        })
        .join('\n      ');

    const projectInitCall = projectInit
        ? `if (typeof projectJayInit._clientInit === 'function') {
        console.log('[DevServer] Running client init: project');
        const projectData = ${JSON.stringify(clientInitData['project'] || {})};
        await projectJayInit._clientInit(projectData);
      }`
        : '';

    const clientInitExecution = hasClientInit
        ? `
      // Plugin client initialization (in dependency order)
      ${pluginClientInitCalls}

      // Project client initialization
      ${projectInitCall}
`
        : '';

    const automationImport = enableAutomation
        ? hasSlowViewState
            ? `import { wrapWithAutomation, AUTOMATION_CONTEXT } from "@jay-framework/runtime-automation";
      import { registerGlobalContext } from "@jay-framework/runtime";
      import { deepMergeViewStates } from "@jay-framework/view-state-merge";`
            : `import { wrapWithAutomation, AUTOMATION_CONTEXT } from "@jay-framework/runtime-automation";
      import { registerGlobalContext } from "@jay-framework/runtime";`
        : '';

    const slowViewStateDecl =
        enableAutomation && hasSlowViewState
            ? `const slowViewState = ${JSON.stringify(slowViewState)};`
            : '';

    return {
        partImports,
        compositeParts,
        pluginClientInitImports,
        projectInitImport,
        clientInitExecution,
        automationImport,
        slowViewStateDecl,
    };
}

/**
 * Generate the automation wrapping code.
 * @param mode - 'client' appends to DOM; 'hydrate' skips appendChild (DOM already present)
 */
export function buildAutomationWrap(
    options: GenerateClientScriptOptions,
    mode: 'client' | 'hydrate',
): string {
    const { enableAutomation = true, slowViewState } = options;
    const hasSlowViewState = slowViewState && Object.keys(slowViewState).length > 0;
    const appendDom = mode === 'client';

    if (!enableAutomation) {
        return appendDom ? `\n      target.appendChild(instance.element.dom);` : '';
    }

    const appendLine = appendDom ? `\n      target.appendChild(wrapped.element.dom);` : '';

    if (hasSlowViewState) {
        return `
      // Wrap with automation for dev tooling
      // Deep merge slow+fast ViewState so automation can see full page state
      const fullViewState = deepMergeViewStates(slowViewState, {...viewState, ...fastCarryForward}, trackByMap);
      const wrapped = wrapWithAutomation(instance, { initialViewState: fullViewState, trackByMap });
      registerGlobalContext(AUTOMATION_CONTEXT, wrapped.automation);
      window.__jay = window.__jay || {};
      window.__jay.automation = wrapped.automation;
      window.dispatchEvent(new Event('jay:automation-ready'));${appendLine}`;
    }

    return `
      // Wrap with automation for dev tooling
      const wrapped = wrapWithAutomation(instance);
      registerGlobalContext(AUTOMATION_CONTEXT, wrapped.automation);
      window.__jay = window.__jay || {};
      window.__jay.automation = wrapped.automation;
      window.dispatchEvent(new Event('jay:automation-ready'));${appendLine}`;
}

/**
 * Resolve all top-level Promise values in a ViewState object.
 * Returns the ViewState with Promises replaced by their resolved values,
 * plus a list of outcomes for reconstructing Promise.resolve()/Promise.reject()
 * in the client script.
 */
export async function resolveViewStatePromises(viewState: object): Promise<{
    resolved: object;
    outcomes: Array<{ id: string; status: 'resolved' | 'rejected'; value: any }>;
}> {
    const entries = Object.entries(viewState);
    const hasPromises = entries.some(([, v]) => v instanceof Promise);
    if (!hasPromises) return { resolved: viewState, outcomes: [] };

    const result = { ...viewState };
    const outcomes: Array<{ id: string; status: 'resolved' | 'rejected'; value: any }> = [];
    for (const [key, value] of entries) {
        if (value instanceof Promise) {
            try {
                const val = await value;
                (result as any)[key] = val;
                outcomes.push({ id: key, status: 'resolved', value: val });
            } catch (err: any) {
                delete (result as any)[key];
                outcomes.push({
                    id: key,
                    status: 'rejected',
                    value: { message: err?.message ?? String(err) },
                });
            }
        }
    }
    return { resolved: result, outcomes };
}

export async function generateClientScript(
    defaultViewState: object,
    fastCarryForward: object,
    parts: DevServerPagePart[],
    jayHtmlPath: string,
    trackByMap: TrackByMap = {},
    clientInitData: Record<string, Record<string, any>> = {},
    projectInit?: ProjectClientInitInfo,
    pluginInits: PluginClientInitInfo[] = [],
    options: GenerateClientScriptOptions = {},
) {
    // Resolve Promise values and track outcomes for client-side reconstruction.
    const { resolved, outcomes } = await resolveViewStatePromises(defaultViewState);
    defaultViewState = resolved;
    const {
        partImports,
        compositeParts,
        pluginClientInitImports,
        projectInitImport,
        clientInitExecution,
        automationImport,
        slowViewStateDecl,
    } = buildScriptFragments(parts, clientInitData, projectInit, pluginInits, options);
    const automationWrap = buildAutomationWrap(options, 'client');

    return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + TS</title>
  </head>
  <body>
    <div id="target"></div>
    <script type="module">
      import {makeCompositeJayComponent} from "@jay-framework/stack-client-runtime";
      ${automationImport}
      ${pluginClientInitImports}
      ${projectInitImport}
      import { render } from '${jayHtmlPath}';
      ${partImports}${slowViewStateDecl}
      const viewState = ${JSON.stringify(defaultViewState)};
${generatePromiseReconstruction(outcomes)}      
      const fastCarryForward = ${JSON.stringify(fastCarryForward)};
      const trackByMap = ${JSON.stringify(trackByMap)};
${clientInitExecution}
      const target = document.getElementById('target');
      const pageComp = makeCompositeJayComponent(render, viewState, fastCarryForward, ${compositeParts}, trackByMap)

      const instance = pageComp({/* placeholder for page props */})
${automationWrap}
    </script>
  </body>
</html>`;
}
