export { generateComponentRefsDefinitionFile } from './components-files/generator-component-refs';
export * from './components-files/transform-component-bridge';
export * from './components-files/transform-component';
export * from './components-files/ts-utils/extract-imports';
export * from './components-files/generate-imports-file';
export * from './generic-typescript-file/parse-generic-typescript-file';
export * from './components-files/building-blocks/create-ts-source-file-from-source';
export type { CompiledPattern } from './components-files/basic-analyzers/compile-function-split-patterns';
export { transformComponentImports } from './components-files/building-blocks/transform-component-imports';
export { compileFunctionSplitPatternsBlock } from './components-files/basic-analyzers/compile-function-split-patterns';
export { createTsSourceFileFromSource } from './components-files/building-blocks/create-ts-source-file-from-source';
export { FunctionRepositoryBuilder } from './components-files/building-blocks/function-repository-builder';
export * from './jay-html';
