#!/usr/bin/env node

/**
 * Warms Artifactory cache for scoped npm packages.
 * Generated from node_modules — run before yarn install when cache is cold.
 *
 * Usage:
 *   node scripts/check-urls.mjs                    # warms all known URLs
 *   node scripts/check-urls.mjs urls.txt           # reads URLs from file
 */

const URLS = [
  'https://npm.dev.wixpress.com/@csstools%2fcolor-helpers',
  'https://npm.dev.wixpress.com/@isaacs%2ffs-minipass',
  'https://npm.dev.wixpress.com/@csstools%2fcss-tokenizer',
  'https://npm.dev.wixpress.com/@csstools%2fcss-parser-algorithms',
  'https://npm.dev.wixpress.com/@csstools%2fcss-color-parser',
  'https://npm.dev.wixpress.com/@csstools%2fcss-calc',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-react-pure-annotations',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-decorators',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-react-jsx-development',
  'https://npm.dev.wixpress.com/@asamuzakjp%2fcss-color',
  'https://npm.dev.wixpress.com/@napi-rs%2flzma-linux-x64-gnu',
  'https://npm.dev.wixpress.com/@rollup%2fplugin-replace',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-unset-value',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-trigonometric-functions',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-text-decoration-shorthand',
  'https://npm.dev.wixpress.com/@typescript-eslint%2fparser',
  'https://npm.dev.wixpress.com/@inquirer%2fselect',
  'https://npm.dev.wixpress.com/@inquirer%2fsearch',
  'https://npm.dev.wixpress.com/@inquirer%2frawlist',
  'https://npm.dev.wixpress.com/@inquirer%2fpassword',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-stepped-value-functions',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-progressive-custom-properties',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-oklab-function',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-normalize-display-values',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-nested-calc',
  'https://npm.dev.wixpress.com/@rollup%2fplugin-babel',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-is-pseudo-class',
  'https://npm.dev.wixpress.com/@apideck%2fbetter-ajv-errors',
  'https://npm.dev.wixpress.com/@typescript-eslint%2feslint-plugin',
  'https://npm.dev.wixpress.com/@inquirer%2fnumber',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-ic-unit',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-hwb-function',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-font-format-keywords',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-color-function',
  'https://npm.dev.wixpress.com/@csstools%2fpostcss-cascade-layers',
  'https://npm.dev.wixpress.com/@babel%2feslint-parser',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-runtime',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-react-display-name',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-flow-strip-types',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-react-jsx',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-flow',
  'https://npm.dev.wixpress.com/@inquirer%2fconfirm',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-regexp-modifiers',
  'https://npm.dev.wixpress.com/@inquirer%2fcheckbox',
  'https://npm.dev.wixpress.com/@babel%2fplugin-proposal-private-methods',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-explicit-resource-management',
  'https://npm.dev.wixpress.com/@babel%2fplugin-proposal-optional-chaining',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-duplicate-named-capturing-groups-regex',
  'https://npm.dev.wixpress.com/@babel%2fplugin-proposal-numeric-separator',
  'https://npm.dev.wixpress.com/@babel%2fplugin-bugfix-safari-rest-destructuring-rhs-array',
  'https://npm.dev.wixpress.com/@babel%2fplugin-proposal-nullish-coalescing-operator',
  'https://npm.dev.wixpress.com/@babel%2fplugin-proposal-decorators',
  'https://npm.dev.wixpress.com/@babel%2fplugin-bugfix-safari-class-field-initializer-scope',
  'https://npm.dev.wixpress.com/@babel%2fplugin-proposal-class-properties',
  'https://npm.dev.wixpress.com/@babel%2fplugin-bugfix-firefox-class-in-computed-class-key',
  'https://npm.dev.wixpress.com/@babel%2fpreset-react',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-react-jsx-source',
  'https://npm.dev.wixpress.com/@inquirer%2fprompts',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-react-jsx-self',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-react-constant-elements',
  'https://npm.dev.wixpress.com/@inquirer%2finput',
  'https://npm.dev.wixpress.com/@inquirer%2fexpand',
  'https://npm.dev.wixpress.com/@inquirer%2feditor',
  'https://npm.dev.wixpress.com/@jridgewell%2fremapping',
  'https://npm.dev.wixpress.com/@testing-library%2freact',
  'https://npm.dev.wixpress.com/@adobe%2fcss-tools',
  'https://npm.dev.wixpress.com/@alloc%2fquick-lru',
  'https://npm.dev.wixpress.com/@ampproject%2fremapping',
  'https://npm.dev.wixpress.com/@antfu%2futils',
  'https://npm.dev.wixpress.com/@asamuzakjp%2fdom-selector',
  'https://npm.dev.wixpress.com/@babel%2fcode-frame',
  'https://npm.dev.wixpress.com/@babel%2fcompat-data',
  'https://npm.dev.wixpress.com/@babel%2fcore',
  'https://npm.dev.wixpress.com/@babel%2fgenerator',
  'https://npm.dev.wixpress.com/@babel%2fhelper-annotate-as-pure',
  'https://npm.dev.wixpress.com/@babel%2fhelper-builder-binary-assignment-operator-visitor',
  'https://npm.dev.wixpress.com/@babel%2fhelper-compilation-targets',
  'https://npm.dev.wixpress.com/@babel%2fhelper-create-class-features-plugin',
  'https://npm.dev.wixpress.com/@babel%2fhelper-create-regexp-features-plugin',
  'https://npm.dev.wixpress.com/@babel%2fhelper-define-polyfill-provider',
  'https://npm.dev.wixpress.com/@babel%2fhelper-environment-visitor',
  'https://npm.dev.wixpress.com/@babel%2fhelper-function-name',
  'https://npm.dev.wixpress.com/@babel%2fhelper-hoist-variables',
  'https://npm.dev.wixpress.com/@babel%2fhelper-member-expression-to-functions',
  'https://npm.dev.wixpress.com/@babel%2fhelper-module-imports',
  'https://npm.dev.wixpress.com/@babel%2fhelper-module-transforms',
  'https://npm.dev.wixpress.com/@babel%2fhelper-optimise-call-expression',
  'https://npm.dev.wixpress.com/@babel%2fhelper-plugin-utils',
  'https://npm.dev.wixpress.com/@babel%2fhelper-remap-async-to-generator',
  'https://npm.dev.wixpress.com/@babel%2fhelper-replace-supers',
  'https://npm.dev.wixpress.com/@babel%2fhelper-simple-access',
  'https://npm.dev.wixpress.com/@babel%2fhelper-skip-transparent-expression-wrappers',
  'https://npm.dev.wixpress.com/@babel%2fhelper-split-export-declaration',
  'https://npm.dev.wixpress.com/@babel%2fhelper-string-parser',
  'https://npm.dev.wixpress.com/@babel%2fhelper-validator-identifier',
  'https://npm.dev.wixpress.com/@babel%2fhelper-validator-option',
  'https://npm.dev.wixpress.com/@babel%2fhelper-wrap-function',
  'https://npm.dev.wixpress.com/@babel%2fhelpers',
  'https://npm.dev.wixpress.com/@babel%2fhighlight',
  'https://npm.dev.wixpress.com/@babel%2fparser',
  'https://npm.dev.wixpress.com/@babel%2fplugin-bugfix-safari-id-destructuring-collision-in-function-expression',
  'https://npm.dev.wixpress.com/@babel%2fplugin-bugfix-v8-spread-parameters-in-optional-chaining',
  'https://npm.dev.wixpress.com/@babel%2fplugin-bugfix-v8-static-class-fields-redefine-readonly',
  'https://npm.dev.wixpress.com/@babel%2fplugin-proposal-private-property-in-object',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-async-generators',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-class-properties',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-class-static-block',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-dynamic-import',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-export-namespace-from',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-import-assertions',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-import-attributes',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-import-meta',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-json-strings',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-jsx',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-logical-assignment-operators',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-nullish-coalescing-operator',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-numeric-separator',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-object-rest-spread',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-optional-catch-binding',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-optional-chaining',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-private-property-in-object',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-top-level-await',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-typescript',
  'https://npm.dev.wixpress.com/@babel%2fplugin-syntax-unicode-sets-regex',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-arrow-functions',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-async-generator-functions',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-async-to-generator',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-block-scoped-functions',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-block-scoping',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-class-properties',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-class-static-block',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-classes',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-computed-properties',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-destructuring',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-dotall-regex',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-duplicate-keys',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-dynamic-import',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-exponentiation-operator',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-export-namespace-from',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-for-of',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-function-name',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-json-strings',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-literals',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-logical-assignment-operators',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-member-expression-literals',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-modules-amd',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-modules-commonjs',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-modules-systemjs',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-modules-umd',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-named-capturing-groups-regex',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-new-target',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-nullish-coalescing-operator',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-numeric-separator',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-object-rest-spread',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-object-super',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-optional-catch-binding',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-optional-chaining',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-parameters',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-private-methods',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-private-property-in-object',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-property-literals',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-regenerator',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-reserved-words',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-shorthand-properties',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-spread',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-sticky-regex',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-template-literals',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-typeof-symbol',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-typescript',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-unicode-escapes',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-unicode-property-regex',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-unicode-regex',
  'https://npm.dev.wixpress.com/@babel%2fplugin-transform-unicode-sets-regex',
  'https://npm.dev.wixpress.com/@babel%2fpreset-env',
  'https://npm.dev.wixpress.com/@babel%2fpreset-modules',
  'https://npm.dev.wixpress.com/@babel%2fpreset-typescript',
  'https://npm.dev.wixpress.com/@babel%2fregjsgen',
  'https://npm.dev.wixpress.com/@babel%2fruntime',
  'https://npm.dev.wixpress.com/@babel%2ftemplate',
  'https://npm.dev.wixpress.com/@babel%2ftraverse',
  'https://npm.dev.wixpress.com/@babel%2ftypes',
  'https://npm.dev.wixpress.com/@bcoe%2fv8-coverage',
  'https://npm.dev.wixpress.com/@caiogondim%2fstrip-margin',
  'https://npm.dev.wixpress.com/@capsizecss%2fcore',
  'https://npm.dev.wixpress.com/@capsizecss%2fmetrics',
  'https://npm.dev.wixpress.com/@capsizecss%2funpack',
  'https://npm.dev.wixpress.com/@csstools%2fnormalize.css',
  'https://npm.dev.wixpress.com/@csstools%2fselector-specificity',
  'https://npm.dev.wixpress.com/@esbuild%2fdarwin-arm64',
  'https://npm.dev.wixpress.com/@eslint-community%2feslint-utils',
  'https://npm.dev.wixpress.com/@eslint-community%2fregexpp',
  'https://npm.dev.wixpress.com/@eslint%2feslintrc',
  'https://npm.dev.wixpress.com/@eslint%2fjs',
  'https://npm.dev.wixpress.com/@google%2fgenai',
  'https://npm.dev.wixpress.com/@humanwhocodes%2fconfig-array',
  'https://npm.dev.wixpress.com/@humanwhocodes%2fmodule-importer',
  'https://npm.dev.wixpress.com/@humanwhocodes%2fobject-schema',
  'https://npm.dev.wixpress.com/@inquirer%2fansi',
  'https://npm.dev.wixpress.com/@inquirer%2ffigures',
  'https://npm.dev.wixpress.com/@isaacs%2fcliui',
  'https://npm.dev.wixpress.com/@istanbuljs%2fload-nyc-config',
  'https://npm.dev.wixpress.com/@istanbuljs%2fschema',
  'https://npm.dev.wixpress.com/@jest%2fconsole',
  'https://npm.dev.wixpress.com/@jest%2fcore',
  'https://npm.dev.wixpress.com/@jest%2fenvironment',
  'https://npm.dev.wixpress.com/@jest%2fexpect-utils',
  'https://npm.dev.wixpress.com/@jest%2ffake-timers',
  'https://npm.dev.wixpress.com/@jest%2fglobals',
  'https://npm.dev.wixpress.com/@jest%2freporters',
  'https://npm.dev.wixpress.com/@jest%2fschemas',
  'https://npm.dev.wixpress.com/@jest%2fsource-map',
  'https://npm.dev.wixpress.com/@jest%2ftest-result',
  'https://npm.dev.wixpress.com/@jest%2ftest-sequencer',
  'https://npm.dev.wixpress.com/@jest%2ftransform',
  'https://npm.dev.wixpress.com/@jest%2ftypes',
  'https://npm.dev.wixpress.com/@jridgewell%2fgen-mapping',
  'https://npm.dev.wixpress.com/@jridgewell%2fresolve-uri',
  'https://npm.dev.wixpress.com/@jridgewell%2fset-array',
  'https://npm.dev.wixpress.com/@jridgewell%2fsource-map',
  'https://npm.dev.wixpress.com/@jridgewell%2fsourcemap-codec',
  'https://npm.dev.wixpress.com/@jridgewell%2ftrace-mapping',
  'https://npm.dev.wixpress.com/@leichtgewicht%2fip-codec',
  'https://npm.dev.wixpress.com/@nicolo-ribaudo%2feslint-scope-5-internals',
  'https://npm.dev.wixpress.com/@nodelib%2ffs.scandir',
  'https://npm.dev.wixpress.com/@nodelib%2ffs.stat',
  'https://npm.dev.wixpress.com/@nodelib%2ffs.walk',
  'https://npm.dev.wixpress.com/@npmcli%2fagent',
  'https://npm.dev.wixpress.com/@npmcli%2ffs',
  'https://npm.dev.wixpress.com/@one-ini%2fwasm',
  'https://npm.dev.wixpress.com/@pkgjs%2fparseargs',
  'https://npm.dev.wixpress.com/@playwright%2ftest',
  'https://npm.dev.wixpress.com/@pmmmwh%2freact-refresh-webpack-plugin',
  'https://npm.dev.wixpress.com/@polka%2furl',
  'https://npm.dev.wixpress.com/@rollup%2fplugin-node-resolve',
  'https://npm.dev.wixpress.com/@rollup%2fpluginutils',
  'https://npm.dev.wixpress.com/@rollup%2frollup-darwin-arm64',
  'https://npm.dev.wixpress.com/@rtsao%2fscc',
  'https://npm.dev.wixpress.com/@rushstack%2feslint-patch',
  'https://npm.dev.wixpress.com/@sinclair%2ftypebox',
  'https://npm.dev.wixpress.com/@sinonjs%2fcommons',
  'https://npm.dev.wixpress.com/@sinonjs%2ffake-timers',
  'https://npm.dev.wixpress.com/@socket.io%2fcomponent-emitter',
  'https://npm.dev.wixpress.com/@surma%2frollup-plugin-off-main-thread',
  'https://npm.dev.wixpress.com/@svgr%2fbabel-plugin-add-jsx-attribute',
  'https://npm.dev.wixpress.com/@svgr%2fbabel-plugin-remove-jsx-attribute',
  'https://npm.dev.wixpress.com/@svgr%2fbabel-plugin-remove-jsx-empty-expression',
  'https://npm.dev.wixpress.com/@svgr%2fbabel-plugin-replace-jsx-attribute-value',
  'https://npm.dev.wixpress.com/@svgr%2fbabel-plugin-svg-dynamic-title',
  'https://npm.dev.wixpress.com/@svgr%2fbabel-plugin-svg-em-dimensions',
  'https://npm.dev.wixpress.com/@svgr%2fbabel-plugin-transform-react-native-svg',
  'https://npm.dev.wixpress.com/@svgr%2fbabel-plugin-transform-svg-component',
  'https://npm.dev.wixpress.com/@svgr%2fbabel-preset',
  'https://npm.dev.wixpress.com/@svgr%2fcore',
  'https://npm.dev.wixpress.com/@svgr%2fhast-util-to-babel-ast',
  'https://npm.dev.wixpress.com/@svgr%2fplugin-jsx',
  'https://npm.dev.wixpress.com/@svgr%2fplugin-svgo',
  'https://npm.dev.wixpress.com/@svgr%2fwebpack',
  'https://npm.dev.wixpress.com/@testing-library%2fdom',
  'https://npm.dev.wixpress.com/@testing-library%2fjest-dom',
  'https://npm.dev.wixpress.com/@testing-library%2fuser-event',
  'https://npm.dev.wixpress.com/@tootallnate%2fonce',
  'https://npm.dev.wixpress.com/@trysound%2fsax',
  'https://npm.dev.wixpress.com/@types%2faria-query',
  'https://npm.dev.wixpress.com/@types%2fbabel__core',
  'https://npm.dev.wixpress.com/@types%2fbabel__generator',
  'https://npm.dev.wixpress.com/@types%2fbabel__template',
  'https://npm.dev.wixpress.com/@types%2fbabel__traverse',
  'https://npm.dev.wixpress.com/@types%2fbody-parser',
  'https://npm.dev.wixpress.com/@types%2fbonjour',
  'https://npm.dev.wixpress.com/@types%2fbusboy',
  'https://npm.dev.wixpress.com/@types%2fchai',
  'https://npm.dev.wixpress.com/@types%2fconnect',
  'https://npm.dev.wixpress.com/@types%2fconnect-history-api-fallback',
  'https://npm.dev.wixpress.com/@types%2fcors',
  'https://npm.dev.wixpress.com/@types%2fdeep-eql',
  'https://npm.dev.wixpress.com/@types%2feslint',
  'https://npm.dev.wixpress.com/@types%2festree',
  'https://npm.dev.wixpress.com/@types%2fexpress',
  'https://npm.dev.wixpress.com/@types%2fexpress-serve-static-core',
  'https://npm.dev.wixpress.com/@types%2ffs-extra',
  'https://npm.dev.wixpress.com/@types%2fglob',
  'https://npm.dev.wixpress.com/@types%2fgraceful-fs',
  'https://npm.dev.wixpress.com/@types%2fhtml-minifier-terser',
  'https://npm.dev.wixpress.com/@types%2fhttp-errors',
  'https://npm.dev.wixpress.com/@types%2fhttp-proxy',
  'https://npm.dev.wixpress.com/@types%2fistanbul-lib-coverage',
  'https://npm.dev.wixpress.com/@types%2fistanbul-lib-report',
  'https://npm.dev.wixpress.com/@types%2fistanbul-reports',
  'https://npm.dev.wixpress.com/@types%2fjest',
  'https://npm.dev.wixpress.com/@types%2fjs-beautify',
  'https://npm.dev.wixpress.com/@types%2fjs-yaml',
  'https://npm.dev.wixpress.com/@types%2fjsdom',
  'https://npm.dev.wixpress.com/@types%2fjson-schema',
  'https://npm.dev.wixpress.com/@types%2fjson5',
  'https://npm.dev.wixpress.com/@types%2fmime',
  'https://npm.dev.wixpress.com/@types%2fminimatch',
  'https://npm.dev.wixpress.com/@types%2fnode',
  'https://npm.dev.wixpress.com/@types%2fnode-forge',
  'https://npm.dev.wixpress.com/@types%2fnormalize-package-data',
  'https://npm.dev.wixpress.com/@types%2fpapaparse',
  'https://npm.dev.wixpress.com/@types%2fparse-json',
  'https://npm.dev.wixpress.com/@types%2fprettier',
  'https://npm.dev.wixpress.com/@types%2fprop-types',
  'https://npm.dev.wixpress.com/@types%2fq',
  'https://npm.dev.wixpress.com/@types%2fqs',
  'https://npm.dev.wixpress.com/@types%2frange-parser',
  'https://npm.dev.wixpress.com/@types%2freact',
  'https://npm.dev.wixpress.com/@types%2freact-dom',
  'https://npm.dev.wixpress.com/@types%2fresolve',
  'https://npm.dev.wixpress.com/@types%2fretry',
  'https://npm.dev.wixpress.com/@types%2fscheduler',
  'https://npm.dev.wixpress.com/@types%2fsemver',
  'https://npm.dev.wixpress.com/@types%2fsend',
  'https://npm.dev.wixpress.com/@types%2fserve-index',
  'https://npm.dev.wixpress.com/@types%2fserve-static',
  'https://npm.dev.wixpress.com/@types%2fshelljs',
  'https://npm.dev.wixpress.com/@types%2fsockjs',
  'https://npm.dev.wixpress.com/@types%2fstack-utils',
  'https://npm.dev.wixpress.com/@types%2ftesting-library__jest-dom',
  'https://npm.dev.wixpress.com/@types%2ftough-cookie',
  'https://npm.dev.wixpress.com/@types%2ftrusted-types',
  'https://npm.dev.wixpress.com/@types%2fuuid',
  'https://npm.dev.wixpress.com/@types%2fws',
  'https://npm.dev.wixpress.com/@types%2fyargs',
  'https://npm.dev.wixpress.com/@types%2fyargs-parser',
  'https://npm.dev.wixpress.com/@typescript-eslint%2fexperimental-utils',
  'https://npm.dev.wixpress.com/@typescript-eslint%2fscope-manager',
  'https://npm.dev.wixpress.com/@typescript-eslint%2ftypes',
  'https://npm.dev.wixpress.com/@typescript-eslint%2ftypescript-estree',
  'https://npm.dev.wixpress.com/@typescript-eslint%2futils',
  'https://npm.dev.wixpress.com/@typescript-eslint%2fvisitor-keys',
  'https://npm.dev.wixpress.com/@ungap%2fstructured-clone',
  'https://npm.dev.wixpress.com/@vitejs%2fplugin-react',
  'https://npm.dev.wixpress.com/@vitest%2fexpect',
  'https://npm.dev.wixpress.com/@vitest%2fpretty-format',
  'https://npm.dev.wixpress.com/@vitest%2frunner',
  'https://npm.dev.wixpress.com/@vitest%2fsnapshot',
  'https://npm.dev.wixpress.com/@vitest%2fspy',
  'https://npm.dev.wixpress.com/@vitest%2futils',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fast',
  'https://npm.dev.wixpress.com/@webassemblyjs%2ffloating-point-hex-parser',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fhelper-api-error',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fhelper-buffer',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fhelper-numbers',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fhelper-wasm-bytecode',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fhelper-wasm-section',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fieee754',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fleb128',
  'https://npm.dev.wixpress.com/@webassemblyjs%2futf8',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fwasm-edit',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fwasm-gen',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fwasm-opt',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fwasm-parser',
  'https://npm.dev.wixpress.com/@webassemblyjs%2fwast-printer',
  'https://npm.dev.wixpress.com/@xtuc%2fieee754',
  'https://npm.dev.wixpress.com/@xtuc%2flong',
];

async function checkUrl(url) {
  const start = Date.now();
  try {
    const res = await fetch(url, { method: 'HEAD', redirect: 'follow' });
    const ms = Date.now() - start;
    return { url, status: res.status, ok: res.ok, ms };
  } catch (err) {
    const ms = Date.now() - start;
    return { url, status: 0, ok: false, ms, error: err.message };
  }
}

async function loadUrls() {
  const arg = process.argv[2];
  if (arg) {
    const fs = await import('node:fs/promises');
    const content = await fs.readFile(arg, 'utf-8');
    return content
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith('#'));
  }
  return URLS;
}

async function main() {
  const urls = await loadUrls();
  console.log(`Warming ${urls.length} URLs...\n`);

  const results = await Promise.all(urls.map(checkUrl));

  const passed = results.filter((r) => r.ok);
  const failed = results.filter((r) => !r.ok);

  for (const r of failed) {
    const detail = r.error || `HTTP ${r.status}`;
    console.log(`  ❌ ${detail} ${r.url} (${r.ms}ms)`);
  }

  console.log(`\n${passed.length} passed, ${failed.length} failed`);
  if (failed.length > 0) process.exit(1);
}

main();
